{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cy.ease",
    "module": "kit",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "kit-1.0.1.aar",
          "url": "kit-1.0.1.aar",
          "size": 177020,
          "sha512": "f316c3446f2a1cd8408e74a89ba054a1dc5b25f8af44738fc500cbfa5a41eaace5883cd30343b9d659bc080c3540b1f158cb9e66c1c009fd3ddf9e30d239134c",
          "sha256": "70808842b8e8b48259dea7602b5252f229ee54e6b62c58fa3b29838b357a5851",
          "sha1": "505a71f1235d3149080caed2ad7fdfa3013df06e",
          "md5": "d64e8fa3b5dc1a785d06337e3dfc9e17"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.18.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "kit-1.0.1.aar",
          "url": "kit-1.0.1.aar",
          "size": 177020,
          "sha512": "f316c3446f2a1cd8408e74a89ba054a1dc5b25f8af44738fc500cbfa5a41eaace5883cd30343b9d659bc080c3540b1f158cb9e66c1c009fd3ddf9e30d239134c",
          "sha256": "70808842b8e8b48259dea7602b5252f229ee54e6b62c58fa3b29838b357a5851",
          "sha1": "505a71f1235d3149080caed2ad7fdfa3013df06e",
          "md5": "d64e8fa3b5dc1a785d06337e3dfc9e17"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kit-1.0.1-sources.jar",
          "url": "kit-1.0.1-sources.jar",
          "size": 39686,
          "sha512": "b5a6a9564cbf8cd4b9939ed0c4ae273b7bb376a5c5c9d679f8b1a4a428f580b4ee7552205734bf55efdaffbcc8beb2566f55dc2246b9efbaedfbc662c5576654",
          "sha256": "e6febaa8db87eac35a223229730ee6e8b849b00449ee8ed451f3003cc5f49b34",
          "sha1": "9996fd1e757f04a85c838ca0a86cf70665b204bb",
          "md5": "9cef12311939c16470d1fb5e7b5ebe8d"
        }
      ]
    }
  ]
}
