{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cy.ease",
    "module": "kit",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "kit-1.0.4.aar",
          "url": "kit-1.0.4.aar",
          "size": 179660,
          "sha512": "e8f6332ab67a2cccf5940548d3ac6f39199b773c289d07e1567fa302bc6fe6859c674940a5788847aefd98ce768f55f15acd58523424c3223094375476a48525",
          "sha256": "cf5904c908e62a9f67b053b682db29e20f88ab16e689e1a15f76d83e1156101f",
          "sha1": "ed534e95af6ab9003c01f8db78972b346a44085c",
          "md5": "8f49a7f71a3b467acfff89647434e915"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.18.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "kit-1.0.4.aar",
          "url": "kit-1.0.4.aar",
          "size": 179660,
          "sha512": "e8f6332ab67a2cccf5940548d3ac6f39199b773c289d07e1567fa302bc6fe6859c674940a5788847aefd98ce768f55f15acd58523424c3223094375476a48525",
          "sha256": "cf5904c908e62a9f67b053b682db29e20f88ab16e689e1a15f76d83e1156101f",
          "sha1": "ed534e95af6ab9003c01f8db78972b346a44085c",
          "md5": "8f49a7f71a3b467acfff89647434e915"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kit-1.0.4-sources.jar",
          "url": "kit-1.0.4-sources.jar",
          "size": 39990,
          "sha512": "df33677f8ae6ebba530f0a4684816bbaad6bc01a0d5c1c02efd74a7090639df38dd62cc96b6577c83b53c709b4a53926174f68b661cd35b8b473b15fa0764890",
          "sha256": "3f9a076d5d0099d91f5c504398f79aa5a73ebbd95f9b8b6885b9e97506e293b6",
          "sha1": "ed96dfa5ed93f9efaa884edcd754dc0149186d40",
          "md5": "9e7298d8647869dd8b0523eec2c25215"
        }
      ]
    }
  ]
}
