{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cy.ease",
    "module": "kit",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "kit-1.0.3.aar",
          "url": "kit-1.0.3.aar",
          "size": 176949,
          "sha512": "a383f1ffca6d53590ca1842f74f74bfd10df12f879eb03c5fdc537107c28e0df18f247386fd79a813df36a27dee01268f71914eff4f03c37dacae47b24f498b9",
          "sha256": "b55b3209633aa7ce7f40fac6c73c9d815a6ae4a106e00e2a360d583be646ce75",
          "sha1": "f1d8c734529b0ca1f7148270cc65e85e583ade36",
          "md5": "607bb3071993b7ca4bb3d656c8108e4b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.18.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "kit-1.0.3.aar",
          "url": "kit-1.0.3.aar",
          "size": 176949,
          "sha512": "a383f1ffca6d53590ca1842f74f74bfd10df12f879eb03c5fdc537107c28e0df18f247386fd79a813df36a27dee01268f71914eff4f03c37dacae47b24f498b9",
          "sha256": "b55b3209633aa7ce7f40fac6c73c9d815a6ae4a106e00e2a360d583be646ce75",
          "sha1": "f1d8c734529b0ca1f7148270cc65e85e583ade36",
          "md5": "607bb3071993b7ca4bb3d656c8108e4b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kit-1.0.3-sources.jar",
          "url": "kit-1.0.3-sources.jar",
          "size": 39645,
          "sha512": "5d4c5826c7480f1863e87d60a7d8cd8a82072f6016100fd7a63dfee4da3b68d81d0b24247c54be12b1f1a8849d8fff64c62b6a792c51ea86cfbac2dae083fe48",
          "sha256": "561f03f9a83b6011988f9077267406524946a5aa048be8e0332ec47da266c76a",
          "sha1": "a6a8988f1c8c5111a9d09f90e08b2f7a7032c68f",
          "md5": "b9456442187a65b18efedb82bfa0b74e"
        }
      ]
    }
  ]
}
