{
  "formatVersion": "1.1",
  "component": {
    "group": "com.cy.ease",
    "module": "ui",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "9.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-1.0.0.aar",
          "url": "ui-1.0.0.aar",
          "size": 298058,
          "sha512": "c219ec5d6b6293fda1a9170f5cb1de106a983cc2b62281d01ab5649c34d28a5f725493229fb998be2b85ea843a465ad4904d9f558123b20456762e4e3fd8da89",
          "sha256": "2b756075f872a87881443e7a988b9e1a2d75631c64e6cbc620302cb3ca59d672",
          "sha1": "fc6b64cdce068dc6298e7842aadfefceb10460ea",
          "md5": "b346dc029e92da224ee6ff7dd5d7b8af"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.cy.ease",
          "module": "kit",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.18.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "9.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-1.0.0.aar",
          "url": "ui-1.0.0.aar",
          "size": 298058,
          "sha512": "c219ec5d6b6293fda1a9170f5cb1de106a983cc2b62281d01ab5649c34d28a5f725493229fb998be2b85ea843a465ad4904d9f558123b20456762e4e3fd8da89",
          "sha256": "2b756075f872a87881443e7a988b9e1a2d75631c64e6cbc620302cb3ca59d672",
          "sha1": "fc6b64cdce068dc6298e7842aadfefceb10460ea",
          "md5": "b346dc029e92da224ee6ff7dd5d7b8af"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-1.0.0-sources.jar",
          "url": "ui-1.0.0-sources.jar",
          "size": 61684,
          "sha512": "839065d080d3f7974557eaa704f993b8b96ca54f5e210a0b709bf025cf8247180dd6c29edb5dd2df2f63bd406912742e52f8b6629e9708f5c06f4eb05f939ae3",
          "sha256": "3cc84257e7171707d4172bccd26f72443a7c5442aa070534be504da716d00498",
          "sha1": "6b22604163eaba5926ac9ac68ad67ede3fa37ea1",
          "md5": "4575671d76142ddab8d382432dce61aa"
        }
      ]
    }
  ]
}
